---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drools-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
        storage: 10Gi
  storageClassName: nfs-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drools-workbench
  labels:
    app: drools-workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drools-workbench
  template:
    metadata:
      labels:
        app: drools-workbench
    spec:
      containers:
      - image: jboss/drools-workbench-showcase:latest
        imagePullPolicy: IfNotPresent
        name: drools-workbench
        ports:
          - containerPort: 8080
          - containerPort: 8001
        volumeMounts:
          - name: drools-data
            mountPath: /opt/jboss/wildfly/bin/.niogit
            subPath: wb_git
          - name: drools-data
            mountPath: /opt/jboss/wildfly/standalone/log
            subPath: logs
      volumes:
      - name: drools-data
        persistentVolumeClaim:
          claimName: drools-data
---
apiVersion: v1
kind: Service
metadata:
  name: drools-wb
  labels:
    app: drools-workbench
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30808
  selector:
    app: drools-workbench

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kie-server
  labels:
    app: kie-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kie-server
  template:
    metadata:
      labels:
        app: kie-server
    spec:
      containers:
      - image: jboss/kie-server-showcase:latest
        imagePullPolicy: IfNotPresent
        name: kie-server
        ports:
          - containerPort: 8080
        env:
          - name: KIE_SERVER_CONTROLLER
            value: http://drools-wb:8080/business-central/rest/controller
          - name: KIE_MAVEN_REPO
            value: http://drools-wb:8080/business-central/maven2

