---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-leader
  labels:
    app: jenkins-leader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-leader
  template:
    metadata:
      labels:
        app: jenkins-leader
    spec:
      securityContext:
        fsGroup: 99
        runAsUser: 0
      containers:
        - name: jenkins-leader
          image: jenkins/jenkins:lts
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: docker-sock
              mountPath: /var/run/docker.sock
          ports:
            - containerPort: 8080
            - containerPort: 50000
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-leader
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins-leader
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: jenkins
  selector:
    app: jenkins-leader
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-np
  labels:
    app: jenkins-leader
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  selector:
    app: jenkins-leader