---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-single-conf
  namespace: redis
data:
  redis.conf: |
    appendonly yes
    dir /var/lib/redis
    port 6379

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-single-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: managed-nfs-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis-single
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-single
  template:
    metadata:
      labels:
        app: redis-single
    spec:
      containers:
      - name: redis
        image: redis:5.0.5-alpine
        imagePullPolicy: IfNotPresent
        command:
          - "redis-server"
        args:
          - "/etc/redis/redis.conf"
          - "--protected-mode"
          - "no"
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
        ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
        volumeMounts:
          - name: "redis-conf"
            mountPath: "/etc/redis"
          - name: "redis-data"
            mountPath: "/var/lib/redis"
      volumes:
      - name: "redis-conf"
        configMap:
          name: "redis-single-conf"
          items:
            - key: "redis.conf"
              path: "redis.conf"
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-single-pvc