---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-exporter
  labels:
    app: rocketmq-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-exporter
  template:
    metadata:
      labels:
        app: rocketmq-exporter
    spec:
      containers:
      - name: rocketmq-exporter
        image: 172.25.10.70:1000/library/exporter/redis_exporter:hj1.0.0
        imagePullPolicy: IfNotPresent
        env:
          - name: APP_OPTS
            value: |
              --rocketmq.config.namesrvAddr=rocketmq.hjmos:9876
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        ports:
          - name: metrics
            containerPort: 5557
            protocol: "TCP"

---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5557"
spec:
  ports:
    - port: 5557
      name: metrics
  selector:
    app: rocketmq-exporter
