apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  namespace: $NAMESPACE
data:
  # if you want to deploy n instances of eureka cluster,
  # you should set eureka_service_address: http://eureka-0.eureka:8761/eureka,...,http://eureka-(n-1).eureka:8761/eureka
  eureka_service_address: http://eureka-0.eureka:8761/eureka/,http://eureka-1.eureka:8761/eureka/

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: eureka
  namespace: $NAMESPACE
spec:
  serviceName: 'eureka'
  replicas: 2
  selector:
    matchLabels:
      app: eureka # 符合目标的Pod有此标签
  template:
    metadata:
      labels:
        app: eureka  # Pod副本的标签
    spec:
      containers:
        - name: service-registry
          image: service-registry:$IMAGE_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: $NAMESPACE
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka
  selector:
    app: eureka

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eureka
  namespace: $NAMESPACE
  labels:
    app: eureka
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/stylesheets/(.*)$ /service-registry/stylesheets/$1 redirect;
      rewrite ^/images/(.*)$ /service-registry/images/$1 redirect;
spec:
  rules:
    - http:
        paths:
          - path: /service-registry(/|$)(.*)
            backend:
              serviceName: eureka
              servicePort: 8761
          - path: /eureka
            backend:
              serviceName: eureka
              servicePort: 8761